import AppKit

/// Polls the general pasteboard and reports every new copy together with the frontmost app.
@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onCapture: (CapturedClip) -> Void

    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),   // password managers
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png, .tiff, .init("public.jpeg"), .init("public.heic"), .init("com.compuserve.gif"),
    ]

    init(onCapture: @escaping (CapturedClip) -> Void) {
        self.onCapture = onCapture
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call right after ATFM itself writes to the pasteboard so the write is not recorded again.
    func markOwnChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        let types = pasteboard.types ?? []
        if types.contains(where: { Self.ignoredTypes.contains($0) }) { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let bid = front?.bundleIdentifier, bid == Bundle.main.bundleIdentifier { return }
        let source = SourceApp(name: front?.localizedName, bundleID: front?.bundleIdentifier, path: front?.bundleURL?.path)
        let now = Date()

        // 1. Files (Finder copies)
        if AppSettings.captureFiles,
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            onCapture(CapturedClip(payload: .files(urls), source: source, date: now))
            return
        }

        // 2. Images
        if AppSettings.captureImages, let imageType = Self.imageTypes.first(where: { types.contains($0) }),
           let data = pasteboard.data(forType: imageType), !data.isEmpty {
            let accompanying = pasteboard.string(forType: .string)
            let isPNG = imageType == .png
            let capture = onCapture
            DispatchQueue.global(qos: .userInitiated).async {
                guard let result = ImageProcessing.process(data: data, isPNG: isPNG) else { return }
                let clip = CapturedClip(
                    payload: .image(png: result.png, thumb: result.thumb, width: result.width, height: result.height, text: accompanying),
                    source: source, date: now
                )
                Task { @MainActor in capture(clip) }
            }
            return
        }

        // 3. Plain text
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            onCapture(CapturedClip(payload: .text(string), source: source, date: now))
        }
    }
}
